#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat May 11 19:34:22 CEST 2024
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim uart_top_TB_behav -key {Behavioral:sim_1:Functional:uart_top_TB} -tclbatch uart_top_TB.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/sims0702/Documents/University/phase-3-courses/complex-digital-design/cdd_lab_3/uart_top_TB_behav.wcfg -log simulate.log"
xsim uart_top_TB_behav -key {Behavioral:sim_1:Functional:uart_top_TB} -tclbatch uart_top_TB.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/sims0702/Documents/University/phase-3-courses/complex-digital-design/cdd_lab_3/uart_top_TB_behav.wcfg -log simulate.log

